### ISSUE TITLE
Create CODE-OF-CONDUCT.md file

### ISSUE THREAD

**Issue by Sitanshu-AI** [Learn-Write-Repeat/DevMerch#3] opened 2021-07-10 22:47 UTC
Create code of conduct file to define community standards

**Comment by bhavik-m** [comment] 2021-07-11 01:41
i would like to create code of conduct file can you assign it to me ?

**Comment by Sitanshu-AI** [comment] 2021-07-11 05:26
well i guess the person who creates issue will get assigned.

**Comment by arpit-dwivedi** [comment] 2021-07-11 15:50
@Sitanshu-AI 
Go ahead with it!!

**Comment by swathi-469** [comment] 2021-07-12 05:34
If the issue is open I would like to work on it. Please assign this to me

**Comment by foreverabhi2002** [comment] 2021-07-24 15:39
@arpit-dwivedi Please assign this issue to someone else because @Sitanshu-AI is taking a lot time

**Comment by swathi-469** [comment] 2021-07-24 15:53
Thanks a lot for assigning me

**Comment by swathi-469** [comment] 2021-07-25 14:39
I have made my pull request please look over it

**Comment by foreverabhi2002** [comment] 2021-07-26 14:27
@swathi-469 your pull request has been merged. Good Luck!

**Closed as completed by foreverabhi2002** 2021-07-26 14:27 UTC
Labels: DCP21, Level0
